### ISSUE TITLE
Multiple Errors When Running Code

### ISSUE THREAD

**Issue by avewells** [HaohanWang/SelectAdditiveLearning#2]
Hello, I am trying to run your code and have run into quite a few errors. I am using **Python v2.7** (which I assume you are as well based on your print statement formatting). I am using **Theano v0.9.0**. 

Steps I have taken so far:
1. Downloaded data from Kaggle.
2. Converted the csv feature files to npy files and placed them in directories matching what is found in the code.
3. Ran **pretrainModel/model.py** which successfully completed.
4. I get stuck when running **run.py** with the error:
```
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    error_mini_r = model.update_random(batch)
  File "/Users/ave/anaconda/envs/py27/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Users/ave/anaconda/envs/py27/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/ave/anaconda/envs/py27/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: GpuReshape: cannot reshape input of shape (15, 18000) to shape (15, 66, 306).
Apply node that caused the error: GpuReshape{3}(GpuSubtensor{int32:int32:}.0, TensorConstant{[ 15  66 306]})
Toposort index: 30
Inputs types: [CudaNdarrayType(float32, matrix), TensorType(int64, vector)]
Inputs shapes: [(15, 18000), (3,)]
Inputs strides: [(18000, 1), (8,)]
Inputs values: ['not shown', array([ 15,  66, 306])]
Outputs clients: [[GpuDimShuffle{0,x,1,2}(GpuReshape{3}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

I've looked at this for a bit but am unsure what needs to be changed. I am not sure if this is an easy fix, but I am new to Theano so I figured I would post here before spending a ton of time trying to debug it.

Additionally, in order to get to the error above I had to make several changes from running into other errors:

The first errors I encountered were with `from theano.tensor.signal import downsample` which is in several files. This was a simple fix as Theano just renamed the package to pool so it needed to be changed to `from theano.tensor.signal import pool` and then called as `pool.pool_2d`.

Next, when importing the data in **run.py** I got an error on **line 109 of dataLoader.py**.
`IndexError: too many indices for array`
To fix this I had to change **line 109** to: `videoIDs = np.transpose(np.loadtxt(path + 'MOSI/videoIDs.csv', delimiter=',')[np.newaxis])`

**Comment by HaohanWang** [comment]
Thanks for the information, I have updated the code, please have a look. 
(the code is for video modality now. )
